import * as esbuild from "esbuild";
import { build as viteBuild } from "vite";
import path from "node:path";
import { fileURLToPath } from "node:url";

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");
const repoRoot = path.resolve(root, "../..");

await viteBuild({
  configFile: path.join(root, "vite.config.ts"),
});

await esbuild.build({
  entryPoints: {
    main: path.join(root, "src/main/main.ts"),
    preload: path.join(root, "src/main/preload.ts"),
  },
  outdir: path.join(root, "dist/electron"),
  bundle: true,
  platform: "node",
  format: "esm",
  target: "node20",
  // electron + node-pty (native) stay external and are loaded at runtime.
  external: ["electron", "node-pty"],
  sourcemap: true,
});

// P0-1: bundle the wanwu-native ACP backend into a single self-contained file
// shipped with the app and launched via Electron-as-Node (no pnpm/tsx).
await esbuild.build({
  entryPoints: {
    "wanwu-acp": path.join(repoRoot, "packages/wanwu-cli/src/native/acpServer.ts"),
  },
  outdir: path.join(root, "dist/backend"),
  outExtension: { ".js": ".mjs" },
  bundle: true,
  platform: "node",
  format: "esm",
  target: "node20",
  banner: { js: "// Wanwu-Code bundled ACP backend — generated by build.mjs" },
});

console.log("wanwu-shell build complete → dist/");
